services:
  # ────────────── Web API ──────────────
  - type: web
    name: tiktok-trend-api
    env: node
    plan: free
    buildCommand: |
      # 1) regular deps (this installs puppeteer-core, NOT full puppeteer)
      npm install

      # 2) fetch Chromium into /opt/render/chrome  (outside slug)
      npx puppeteer browsers install chrome --path /opt/render/chrome
    startCommand: node index.js
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: tiktok-db
          property: connectionString
      - key: COOKIE
        value: ""
      # tell Puppeteer where Chrome lives
      - key: PUPPETEER_EXECUTABLE_PATH
        value: /opt/render/chrome/chrome/linux-*/chrome-linux64/chrome

  # ────────────── Cron scraper ──────────────
  - type: cron
    name: tiktok-trend-cron
    env: node
    plan: starter
    buildCommand: |
      npm install
      npx puppeteer browsers install chrome --path /opt/render/chrome
    startCommand: node cron.js
    schedule: "0 */3 * * *"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: tiktok-db
          property: connectionString
      - key: KEYWORDS
        value: "summer outfits,cleaning hacks,bible study"
      - key: COOKIE
        value: ""
      - key: PUPPETEER_EXECUTABLE_PATH
        value: /opt/render/chrome/chrome/linux-*/chrome-linux64/chrome

databases:
  - name: tiktok-db
    plan: free
