# render.yaml
services:
  # Web API
  - type: web
    name: tiktok-trend-api
    env: node
    plan: free
    buildCommand: "npm install"
    startCommand: "node index.js"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: tiktok-db
          property: connectionString
      - key: COOKIE
        value: ""

  # Scheduled scraper (Starter plan required)
  - type: cron
    name: tiktok-trend-cron
    env: node
    plan: starter        # <── cheapest valid plan for cron
    buildCommand: "npm install"
    startCommand: "node cron.js"
    schedule: "0 */3 * * *"   # every 3 h
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: tiktok-db
          property: connectionString
      - key: KEYWORDS
        value: "summer outfits,cleaning hacks,bible study"
      - key: COOKIE
        value: ""

databases:
  - name: tiktok-db
    plan: free
